version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.37
workflows:
  version: 2
  commit:
    jobs:
      - pus/test-backend:
          context: pus
          filters:
            branches:
              ignore:
                - master
                - dev
      - pus/gradle-bygg-og-deploy:
          context: pus
          filepath: ./nais-q.yaml
          filters:
            branches:
              only: dev
      - pus/gradle-bygg-og-deploy:
          context: pus
          filepath: ./nais.yaml
          filters:
            branches:
              only: master
