version: 2.1
orbs:
  pus: navikt/pus-orb@0.0.13

workflows:
  version: 2
  commit:
    jobs:
      - pus/gradle-test:
          context: pus
          filters:
            branches:
              ignore: master
      - pus/gradle-bygg-og-deploy:
          context: pus
          cluster: dev-fss
          filters:
            branches:
              only: master
      - hold:
          requires:
            - pus/gradle-bygg-og-deploy
          type: approval
          filters:
            branches:
              only: master
      - pus/deploy-latest:
          requires:
            - hold
          context: pus
          cluster: dev-fss #TODO: endre denne til prod-fss etterhvert
          filepath: ./nais.yaml
          filters:
            branches:
              only: master